# -*- coding: utf-8 -*-
"""day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VEgSShvBNbScs-ErGyunSyeEQj97pjUd
"""

print("hello")